import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const nunitoFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", "vietnamese"],
});

const fwc26Font = localFont({
  variable: "--font-fwc26",
  src: "../../public/fonts/fwc2026.ttf",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fwc26Font.className} ${nunitoFont.className} antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
